import fs from 'fs-extra';
import path from 'path';
import https from 'https';
import chalk from 'chalk';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface VersionsConfig {
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
}

const PACKAGES = {
  dependencies: ['next', 'react', 'react-dom'],
  devDependencies: [
    'typescript',
    '@types/node',
    '@types/react',
    '@types/react-dom',
    'autoprefixer',
    'eslint',
    'eslint-config-next',
    'postcss',
    'prettier',
    'tailwindcss',
    'turbo',
  ],
};

async function getLatestVersion(pkg: string): Promise<string> {
  return new Promise((resolve, reject) => {
    https.get(`https://registry.npmjs.org/${pkg}/latest`, (res) => {
      let data = '';
      res.on('data', (chunk) => (data += chunk));
      res.on('end', () => {
        try {
          resolve(JSON.parse(data).version);
        } catch (e) {
          reject(new Error(`Failed to parse ${pkg}`));
        }
      });
    }).on('error', reject);
  });
}

async function main() {
  console.log(chalk.blue('🔍 Fetching latest versions...\n'));

  const versions: VersionsConfig = { dependencies: {}, devDependencies: {} };

  console.log(chalk.bold('Dependencies:'));
  for (const pkg of PACKAGES.dependencies) {
    try {
      const ver = await getLatestVersion(pkg);
      versions.dependencies[pkg] = `^${ver}`;
      console.log(chalk.green(`  ✓ ${pkg.padEnd(25)} ^${ver}`));
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      console.log(chalk.red(`  ✗ ${pkg.padEnd(25)} ${errorMessage}`));
    }
  }

  console.log(chalk.bold('\nDev Dependencies:'));
  for (const pkg of PACKAGES.devDependencies) {
    try {
      const ver = await getLatestVersion(pkg);
      versions.devDependencies[pkg] = `^${ver}`;
      console.log(chalk.green(`  ✓ ${pkg.padEnd(25)} ^${ver}`));
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      console.log(chalk.red(`  ✗ ${pkg.padEnd(25)} ${errorMessage}`));
    }
  }

  const content = `// Auto-generated by update-versions script
// Last updated: ${new Date().toISOString()}
// Run 'pnpm update-versions' to update

export const PACKAGE_VERSIONS = {
  dependencies: ${JSON.stringify(versions.dependencies, null, 4)},
  devDependencies: ${JSON.stringify(versions.devDependencies, null, 4)},
} as const;
`;

  const filePath = path.join(__dirname, '../src/config/versions.ts');
  await fs.writeFile(filePath, content);

  console.log(chalk.green('\n✨ versions.ts updated!'));
  console.log(chalk.gray(`   ${filePath}`));
}

main().catch((e) => {
  console.error(chalk.red('\n❌ Error:'), e);
  process.exit(1);
});
