// Auto-generated by update-versions script
// Last updated: 2025-01-17
// Run 'pnpm update-versions' to update

interface PackageVersions {
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
}

export const PACKAGE_VERSIONS: PackageVersions = {
  dependencies: {
    'next': '^15.1.3',
    'react': '^19.0.0',
    'react-dom': '^19.0.0',
  },
  devDependencies: {
    '@types/node': '^22.10.5',
    '@types/react': '^19.0.1',
    '@types/react-dom': '^19.0.2',
    'autoprefixer': '^10.4.20',
    'eslint': '^9.17.0',
    'eslint-config-next': '^15.1.3',
    'postcss': '^8.4.49',
    'prettier': '^3.4.2',
    'tailwindcss': '^4.0.0',
    'turbo': '^2.3.3',
    'typescript': '^5.7.2',
  },
};
